services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: issue_tracker
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    ports:
      - "8088:8088"

  # webserver:
  #   image: nginx:latest
  #   container_name: issue_tracker_webserver
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8090"
  #   networks:
  #     - laravel
  #   depends_on:
  #     - app

networks:
  laravel:
    driver: bridge
